# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum columns of a sparse matrix
#'
#' @export
ColSums <- function(m) {
    .Call('_screamr_ColSums', PACKAGE = 'screamr', m)
}

#' Sum rows of a sparse matrix
#'
#' @export
RowSums <- function(m) {
    .Call('_screamr_RowSums', PACKAGE = 'screamr', m)
}

#' Row variances of sparse matrix
#'
#' @export
ColVars <- function(m) {
    .Call('_screamr_ColVars', PACKAGE = 'screamr', m)
}

